import type { Metadata } from 'next'
import { Reddit_Mono } from 'next/font/google'
import '../globals.css'

const inter = Reddit_Mono({ subsets: ['vietnamese'] })

export const metadata: Metadata = {
    title: {
        default: 'Authentication ',
        template: 'Sweet Coffee | %s',
    },
    description: 'Generated by create next app',
}

export default function EmptyLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <div>Empty Layout</div>
                {children}
            </body>
        </html>
    )
}
