import type { Metadata } from 'next'
import { Reddit_Mono } from 'next/font/google'
import Header from '@/components/common/header'
import '../globals.css'

const inter = Reddit_Mono({ subsets: ['vietnamese'] })

export const metadata: Metadata = {
    title: {
        absolute: '',
        default: 'Sweet Coffee',
        template: 'Sweet Coffee - %s',
    },
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className={`${inter.className} bg-gray-200/30 `}>
                <Header />
                {children}
            </body>
        </html>
    )
}
